// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWlCrok0H5NqvOE6n3h2UnY9-OPE7xJyI',
    appId: '1:850547029095:web:80728d9a70215b54c890c2',
    messagingSenderId: '850547029095',
    projectId: 'whatsapp-clone-24cb6',
    authDomain: 'whatsapp-clone-24cb6.firebaseapp.com',
    storageBucket: 'whatsapp-clone-24cb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW4rK-8_24_T49UhdkC_QP15X8Tb0eyjs',
    appId: '1:850547029095:android:9eaaaadcdccafe7dc890c2',
    messagingSenderId: '850547029095',
    projectId: 'whatsapp-clone-24cb6',
    storageBucket: 'whatsapp-clone-24cb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBOLMk3XKN-GKMotIlxIHqfEYCIJ1oi9I',
    appId: '1:850547029095:ios:ab44586273a4e381c890c2',
    messagingSenderId: '850547029095',
    projectId: 'whatsapp-clone-24cb6',
    storageBucket: 'whatsapp-clone-24cb6.appspot.com',
    androidClientId: '850547029095-rhmkj74ht7eokqk9iu8qkktofnd883at.apps.googleusercontent.com',
    iosClientId: '850547029095-4iumim7b3gai4shc75p5fl15chv6i1n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
